# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'
    ignore:
      # Needs more work.
      - dependency-name: 'eslint*'
      - dependency-name: '@elastic/elasticsearch'
      - dependency-name: 'husky'
      - dependency-name: '@types/node'
      # Needs Node >= 20.15, update when we get there.
      - dependency-name: 'lint-staged'
    groups:
      all:
        patterns: ['*']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      all:
        patterns: ['*']
