version: "3.3"
services:
  tooling:
    build:
      dockerfile: tooling.Dockerfile
      context: .

  api:
    build:
      dockerfile: ./api/Dockerfile
      context: .

  pipeline:
    build:
      dockerfile: ./pipeline/Dockerfile
      context: .

  webhook:
    build:
      dockerfile: ./webhook/Dockerfile
      context: .
