steps:
  - label: "autoformat"
    plugins:
      - docker-compose#v4.10.1:
          run: tooling
          command: .buildkite/scripts/autoformat.sh
          mount-ssh-agent: true
          mount-buildkite-agent: true
    agents:
      queue: nano
