name: Basic template
description: New feature or consideration for the team
projects: 'wellcomecollection/18'
body:
  - type: markdown
    attributes:
      value: |
        ## What
        Context on the issue, links to relevant documentation.

        ## Definition of Ready
        A checklist of what is needed before work can start on this ticket

        ## Definition of Done
        A checklist of what needs to be done before this ticket can be considered closed.

        - [ ] Has been deployed to production
